tg_bot:
  token: # токен бота (str)
  admin_group_id: # ID группы администраторов (int)

db:
  dbms: # название используемой СУБД (str)
  driver: # драйвер для подключения к БД (str)
  host: # хост БД (str)
  port: # порт БД (int)
  user: # пользователь БД (str)
  password: # пароль БД (str)
  database: # название БД (str)
  echo_db: # режим отладки (bool)

scheduler:
  trigger: # тип триггера (str)
  day: # день триггера (str)
  hour: # час триггера (int)
  minute: # минута триггера (int)