"""в медиа добавлены внешние ключи

Revision ID: 0f90a65e8d1e
Revises: 19ec8dcec622
Create Date: 2023-12-30 19:40:10.261931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f90a65e8d1e'
down_revision: Union[str, None] = '19ec8dcec622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('media_type_id', sa.Integer(), nullable=False))
    op.add_column('media', sa.Column('media_block_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'media', 'media_type', ['media_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media', 'media_block', ['media_block_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'media_block_id')
    op.drop_column('media', 'media_type_id')
    # ### end Alembic commands ###
