"""в Picture добавлены столбцы title и created_at

Revision ID: 4e76f989f0bb
Revises: 76e62b1b985c
Create Date: 2024-01-05 13:30:17.259403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e76f989f0bb'
down_revision: Union[str, None] = '76e62b1b985c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('title', sa.String(), nullable=False))
    op.add_column('picture', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'created_at')
    op.drop_column('picture', 'title')
    # ### end Alembic commands ###
