name: build-and-deploy
on:
  push:
    branches:
      #  - main
      - 'feature/cicd'
  pull_request:
    branches:
      #  - main
      - 'feature/cicd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/${{ secrets.DOCKERHUB_IMAGE }}
#          tags: type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
#          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/${{ secrets.DOCKERHUB_IMAGE }}:latest
#          tags: ${{ steps.meta.outputs.tags }}

#  deploy:
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo 'deploying'
